# Generated by Django 4.0 on 2021-12-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Laptops',
        ),
        migrations.AlterModelOptions(
            name='laptops',
            options={'verbose_name': 'Laptop'},
        ),
    ]
