# Generated by Django 4.0 on 2021-12-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_products_laptops_alter_laptops_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laptops',
            new_name='Laptop',
        ),
    ]
