# Generated by Django 4.0 on 2021-12-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_laptops_laptop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laptop',
            new_name='Products',
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product'},
        ),
    ]
