# Generated by Django 4.0 on 2021-12-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_laptop_products_alter_products_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Laptops',
        ),
    ]
