# Generated by Django 4.0 on 2021-12-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_products_laptops'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptops',
            options={'verbose_name': 'Laptop'},
        ),
    ]
