# Generated by Django 4.0 on 2021-12-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_laptops_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptops',
            options={},
        ),
    ]
