# Generated by Django 4.0 on 2021-12-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_laptops_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptops',
            options={'verbose_name': 'Product'},
        ),
    ]
