# Generated by Django 4.0 on 2022-01-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='description',
            field=models.TextField(max_length=159),
        ),
    ]
