# Generated by Django 4.0 on 2022-01-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_laptops_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
